### ISSUE TITLE
[Bug]: Unable to run the init command

### ISSUE THREAD

**Issue by shreekrishnalamichhane** [suparthghimire/ts-template#3]
This error occurred on a fresh project.

![image](https://github.com/user-attachments/assets/8a418d3b-b4f1-472d-9d57-b66e121a3f7c)

**Comment by suparthghimire** [comment]
Fixed on latest version.

The issue:
Inquirer upgraded to use `esm` instead of `cjs`. This package was still in `cjs`. I upgraded it to completely use `esm` now.
